# This is a basic workflow to help you get started with Actions

name: Tencent_cloudbase_static_host

# Controls when the workflow will run
on: [push] # push 代码时触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Tencent Cloudbase Github Action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Deploy static to Tencent CloudBase
        id: deployStatic
        uses: TencentCloudBase/cloudbase-action@v1
        with:
          secretId: ${{ secrets.SECRET_ID }}
          secretKey: ${{ secrets.SECRET_KEY }}
          envId: ${{ secrets.ENV_ID }}
          staticSrcPath: ./
